infer_eval_metric: True
detect_and_drop_id_column: False
task_preprocessors_timeout: 3600
time_limit: 14400
save_artifacts:
  enabled: False
  append_timestamp: True
  path: "./aga-artifacts"
feature_transformers:
  enabled_models: []
  models:
    CAAFE:
      _target_: autogluon.assistant.transformer.feature_transformers.caafe.CAAFETransformer
      eval_model: lightgbm
      llm_provider: ${llm.provider}
      llm_model: ${llm.model}
      num_iterations: 5
      optimization_metric: roc
    OpenFE:
      _target_: autogluon.assistant.transformer.feature_transformers.openfe.OpenFETransformer
      n_jobs: 1
      num_features_to_keep: 10
    PretrainedEmbedding:
      _target_: autogluon.assistant.transformer.feature_transformers.scentenceFT.PretrainedEmbeddingTransformer
      model_name: 'all-mpnet-base-v2'
autogluon:
  predictor_init_kwargs: {}
  predictor_fit_kwargs:
    presets: best_quality
llm:
  # 支持: bedrock, openai, azure, deepseek, ollama
  # provider: bedrock
  # model: "anthropic.claude-3-5-sonnet-20241022-v2:0"
  # provider: openai
  # model: gpt-4o-2024-08-06
  provider: deepseek
  model: deepseek-chat
  api_url: https://api.deepseek.com/v1/chat/completions
  api_key: "sk-27b70027e52345f896856a8830cfb09b"
  # provider: ollama
  # model: llama3
  # api_url: http://localhost:11434/api/chat
  # provider: bedrock
  # model: "anthropic.claude-3-5-sonnet-20241022-v2:0"
  max_tokens: 512
  proxy_url: null
  temperature: 0.7
  verbose: True
